/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/tags/{id}": {
    put: operations["update"];
    delete: operations["delete_1"];
  };
  "/api/v1/outfits/{id}": {
    get: operations["get"];
    put: operations["update_1"];
    delete: operations["delete_2"];
  };
  "/api/v1/outfits/{id}/items/reorder": {
    put: operations["reorder"];
  };
  "/api/v1/clothing/{id}": {
    get: operations["get_1"];
    put: operations["update_2"];
    delete: operations["delete_3"];
  };
  "/api/v1/categories/{id}": {
    put: operations["update_3"];
    delete: operations["delete_4"];
  };
  "/api/v1/calendar/{id}": {
    get: operations["get_2"];
    put: operations["update_4"];
    delete: operations["delete_5"];
  };
  "/api/v1/wear-logs": {
    post: operations["create"];
  };
  "/api/v1/tags": {
    get: operations["list"];
    post: operations["create_1"];
  };
  "/api/v1/outfits": {
    get: operations["list_1"];
    post: operations["create_2"];
  };
  "/api/v1/outfits/{id}/items": {
    post: operations["addItem"];
  };
  "/api/v1/clothing": {
    get: operations["list_2"];
    post: operations["create_3"];
  };
  "/api/v1/clothing/{id}/images": {
    post: operations["uploadImage"];
  };
  "/api/v1/categories": {
    get: operations["list_3"];
    post: operations["create_4"];
  };
  "/api/v1/calendar": {
    get: operations["range"];
    post: operations["create_5"];
  };
  "/api/v1/stats/overview": {
    get: operations["overview"];
  };
  "/api/v1/stats/most-worn": {
    get: operations["mostWorn"];
  };
  "/api/v1/stats/least-worn": {
    get: operations["leastWorn"];
  };
  "/api/v1/stats/clothing/{id}": {
    get: operations["forClothing"];
  };
  "/api/v1/images/**": {
    get: operations["proxy"];
  };
  "/api/v1/wear-logs/{id}": {
    delete: operations["delete"];
  };
  "/api/v1/outfits/{id}/items/{clothingId}": {
    delete: operations["removeItem"];
  };
  "/api/v1/clothing/{id}/images/{imageId}": {
    delete: operations["deleteImage"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    TagRequest: {
      name: string;
    };
    ResultTag: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["Tag"];
    };
    Tag: {
      /** Format: int64 */
      id?: number;
      name?: string;
    };
    OutfitRequest: {
      name: string;
      description?: string;
      occasion?: string;
      season?: string;
      isFavorite?: boolean;
      /** Format: int64 */
      coverImageId?: number;
      clothingIds?: number[];
    };
    Outfit: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      occasion?: string;
      season?: string;
      isFavorite?: boolean;
      /** Format: int64 */
      coverImageId?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ResultOutfit: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["Outfit"];
    };
    ItemOrder: {
      /** Format: int64 */
      clothingId?: number;
      /** Format: int32 */
      sortOrder?: number;
    };
    ResultVoid: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: Record<string, never>;
    };
    ClothingRequest: {
      name: string;
      brand?: string;
      colorPrimary?: string;
      colorSecondary?: string;
      size?: string;
      purchasePrice?: number;
      /** Format: date */
      purchaseDate?: string;
      season?: string;
      notes?: string;
      categoryIds?: number[];
      tagIds?: number[];
    };
    Clothing: {
      /** Format: int64 */
      id?: number;
      name?: string;
      brand?: string;
      colorPrimary?: string;
      colorSecondary?: string;
      size?: string;
      purchasePrice?: number;
      /** Format: date */
      purchaseDate?: string;
      season?: string;
      status?: string;
      notes?: string;
      /** Format: int64 */
      mainImageId?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ResultClothing: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["Clothing"];
    };
    CategoryRequest: {
      name: string;
      /** Format: int64 */
      parentId?: number;
      /** Format: int32 */
      sortOrder?: number;
    };
    Category: {
      /** Format: int64 */
      id?: number;
      name?: string;
      /** Format: int64 */
      parentId?: number;
      /** Format: int32 */
      sortOrder?: number;
    };
    ResultCategory: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["Category"];
    };
    CalendarEntry: {
      /** Format: int64 */
      id?: number;
      /** Format: date */
      entryDate?: string;
      slot?: string;
      /** Format: int64 */
      outfitId?: number;
      notes?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ResultCalendarEntry: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["CalendarEntry"];
    };
    ResultWearLog: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["WearLog"];
    };
    WearLog: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      clothingId?: number;
      /** Format: int64 */
      calendarEntryId?: number;
      /** Format: date */
      wornAt?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    ClothingImage: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      clothingId?: number;
      storageKey?: string;
      /** Format: int32 */
      sortOrder?: number;
      isMain?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    ResultClothingImage: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ClothingImage"];
    };
    ResultListTag: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["Tag"][];
    };
    ResultStatsOverview: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["StatsOverview"];
    };
    StatsOverview: {
      /** Format: int64 */
      totalClothing?: number;
      /** Format: int64 */
      totalOutfits?: number;
      /** Format: int64 */
      monthWears?: number;
    };
    ClothingStat: {
      /** Format: int64 */
      clothingId?: number;
      name?: string;
      /** Format: int64 */
      wearCount?: number;
      /** Format: date */
      firstWorn?: string;
      /** Format: date */
      lastWorn?: string;
      costPerWear?: number;
    };
    ResultListClothingStat: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ClothingStat"][];
    };
    ResultClothingStat: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ClothingStat"];
    };
    IPageOutfitResponse: {
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      current?: number;
      records?: components["schemas"]["OutfitResponse"][];
      /** Format: int64 */
      total?: number;
      /** Format: int64 */
      pages?: number;
    };
    OutfitResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      occasion?: string;
      season?: string;
      isFavorite?: boolean;
      /** Format: int64 */
      coverImageId?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      items?: components["schemas"]["Clothing"][];
    };
    ResultIPageOutfitResponse: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["IPageOutfitResponse"];
    };
    ResultOutfitResponse: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["OutfitResponse"];
    };
    ClothingFilter: {
      /** Format: int64 */
      categoryId?: number;
      /** Format: int64 */
      tagId?: number;
      season?: string;
      status?: string;
      keyword?: string;
      /** Format: int64 */
      page?: number;
      /** Format: int64 */
      size?: number;
    };
    ClothingResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      brand?: string;
      colorPrimary?: string;
      colorSecondary?: string;
      size?: string;
      purchasePrice?: number;
      /** Format: date */
      purchaseDate?: string;
      season?: string;
      notes?: string;
      status?: string;
      /** Format: int64 */
      mainImageId?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      categories?: string[];
      tags?: string[];
      imageKeys?: string[];
    };
    IPageClothingResponse: {
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      current?: number;
      records?: components["schemas"]["ClothingResponse"][];
      /** Format: int64 */
      total?: number;
      /** Format: int64 */
      pages?: number;
    };
    ResultIPageClothingResponse: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["IPageClothingResponse"];
    };
    ResultClothingResponse: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ClothingResponse"];
    };
    ResultListCategory: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["Category"][];
    };
    ResultListCalendarEntry: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["CalendarEntry"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  update: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultTag"];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  get: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultOutfitResponse"];
        };
      };
    };
  };
  update_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OutfitRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultOutfit"];
        };
      };
    };
  };
  delete_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  reorder: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemOrder"][];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  get_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultClothingResponse"];
        };
      };
    };
  };
  update_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClothingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultClothing"];
        };
      };
    };
  };
  delete_3: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  update_3: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultCategory"];
        };
      };
    };
  };
  delete_4: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  get_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultCalendarEntry"];
        };
      };
    };
  };
  update_4: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarEntry"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultCalendarEntry"];
        };
      };
    };
  };
  delete_5: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  create: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultWearLog"];
        };
      };
    };
  };
  list: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultListTag"];
        };
      };
    };
  };
  create_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultTag"];
        };
      };
    };
  };
  list_1: {
    parameters: {
      query?: {
        season?: string;
        occasion?: string;
        favorite?: boolean;
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultIPageOutfitResponse"];
        };
      };
    };
  };
  create_2: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OutfitRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultOutfit"];
        };
      };
    };
  };
  addItem: {
    parameters: {
      query: {
        clothingId: number;
        sortOrder?: number;
      };
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  list_2: {
    parameters: {
      query: {
        filter: components["schemas"]["ClothingFilter"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultIPageClothingResponse"];
        };
      };
    };
  };
  create_3: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClothingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultClothing"];
        };
      };
    };
  };
  uploadImage: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultClothingImage"];
        };
      };
    };
  };
  list_3: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultListCategory"];
        };
      };
    };
  };
  create_4: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultCategory"];
        };
      };
    };
  };
  range: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultListCalendarEntry"];
        };
      };
    };
  };
  create_5: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarEntry"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultCalendarEntry"];
        };
      };
    };
  };
  overview: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultStatsOverview"];
        };
      };
    };
  };
  mostWorn: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultListClothingStat"];
        };
      };
    };
  };
  leastWorn: {
    parameters: {
      query?: {
        days?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultListClothingStat"];
        };
      };
    };
  };
  forClothing: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultClothingStat"];
        };
      };
    };
  };
  proxy: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  removeItem: {
    parameters: {
      path: {
        id: number;
        clothingId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
  deleteImage: {
    parameters: {
      path: {
        id: number;
        imageId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultVoid"];
        };
      };
    };
  };
}
